# Generated by Django 4.2.6 on 2023-12-10 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('catagroy', models.ManyToManyField(to='catagories.catagory')),
            ],
        ),
    ]
